### ISSUE TITLE
Default Numba cache to True

### ISSUE THREAD

**Issue by gipert** [legend-exp/dspeed#16]
We should stick to Numba's default (`True`) here:

https://github.com/legend-exp/dspeed/blob/30ac25155e3fe076b184fa962883dd9f8ca22584/src/dspeed/utils.py#L48

If the LEGEND data production needs to turn it off, it can do that easily.

**Comment by gipert** [comment]
I was mistaken. Caching is actually off by default and has several limitations:

https://numba.readthedocs.io/en/stable/user/jit.html#cache

So this needs to be re-discussed. Now I'm more in favor of keeping it disabled and advertise the feature to users.

**Comment by gipert** [comment]
Though I think it's safe enough to turn on for compression routines, see https://github.com/legend-exp/legend-pydataobj/pull/22.

**Comment by iguinn** [comment]
I think caching should be safe for the routines we use it for:

**The caching of compiled functions is not performed on a function-by-function basis. The cached function is the the main jit function, and all secondary functions (those called by the main function) are incorporated in the cache of the main function.**
I think this is the biggest risk, since changes to numba itself would not be updated (e.g. if they updated their implementation of one of the numpy functions we call, or something like that). Otherwise, I don't think we are calling secondary functions in any of the ones we cache.

**Cache invalidation fails to recognize changes in functions defined in a different file. This means that when a main jit function calls functions that were imported from a different module, a change in those other modules will not be detected and the cache will not be updated. This carries the risk that “old” function code might be used in the calculations.**
I don't think this will cause any problems

**Global variables are treated as constants. The cache will remember the value of the global variable at compilation time. On cache load, the cached function will not rebind to the new value of the global variable.**
Global variables are used in our factory functions, but these are also not cached for this very reason

Overall, I think caching is unlikely to cause problems. If we did want to mitigate it, we could try to figure out how to delete the cache if you update pygama.

**Comment by gipert** [comment]
Sounds good. The location of the Numba cache is documented here: https://numba.readthedocs.io/en/stable/reference/envvars.html#envvar-NUMBA_CACHE_DIR. It should be sufficient to remove that directory, in order to clear the cache.

**Comment by iguinn** [comment]
Looking at a more updated version of the numba documentation (https://numba.readthedocs.io/en/stable/developer/caching.html) it no longer lists "The caching of compiled functions is not performed on a function-by-function basis. The cached function is the the main jit function, and all secondary functions (those called by the main function) are incorporated in the cache of the main function." as a problem, so I actually think that defaulting caching to true is quite safe now. The other two issues can be avoided by overriding the cache default in the numba decorator.

They also have more details about the caching location than I remember seeing in the past: https://numba.readthedocs.io/en/stable/reference/envvars.html#numba-envvars-caching. The first option is the "in-tree cache", which will apply to user installs of pygama but not to system or container installs. The second option is to use the appdirs package (https://github.com/ActiveState/appdirs), which points to `$HOME/.cache/numba/dspeed_[hexstring]`. I'm not sure what the hexstring is. I will also look into whether this is something that can be changed...It might be possible that we could create a `DSPEED_CACHE` environment variable to override this.

**Comment by iguinn** [comment]
It looks like the only way to modify the caching directory would be through `numba.config.CACHE_DIR`, which contains the content of the `NUMBA_CACHE_DIR` environment variable. This means, we could do something like override when running dspeed, but this would also override it for other libraries which could easily have some unintended consequences...For now, I won't do anything with this.

**Comment by iguinn** [comment]
The hexstring is a hash of the directory containing the module it looks like. It's defined here https://github.com/numba/numba/blob/main/numba/core/caching.py in get_suitable_cache_subpath. This must be intended to make sure that if you have multiple versions installed, the caches don't interfere with each other.
